server:
  port: 8005

spring:
  application:
    name: ierp-auth-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    # 是否从EurekaServer 抓取已有的注册信息 默认为true  单节点无所谓，集群必须设置为true 才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka  #地址
      defaultZone: http://ierp-server:7001/eureka #集群版
  instance:
    instance-id: auth-service  #服务名称
    prefer-ip-address: true  #访问路径显示ip

