server:
  port: 9527
spring:
  application:
    name: ierp-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由

      routes:
        - id: ierp_test #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #        uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://ierp-client
          predicates:
            - Path=/client/school/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: ierp-gateway
    prefer-ip-address: true  #访问路径显示ip
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ierp-server:7001/eureka  #集群版  单机版吧,后去掉即可

